name: Check
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@master
        with:
          node-version: '22.x'
      - name: Corepack
        run: corepack enable
      - name: Install
        run: yarn install
      - name: Depcheck
        run: yarn depcheck
      - name: Prettier
        run: yarn prettier
      - name: Lint
        run: yarn next lint
      - name: Build
        run: yarn build
      - name: Sitemap
        run: yarn sitemap
